const D='د.ع';let products=[];let invoices=[];let cart=[];let invoiceMode='quick';
const money=n=>Number(n||0).toLocaleString('en-US')+' '+D;const save=()=>{cloudSaveAll().catch(e=>toast('تعذر الحفظ: '+e.message))};
function go(id){const req={cashier:'cashier',products:'products',inventory:'products',invoices:'invoices',repairs:'repairs',debts:'debts',reports:'reports',settings:'settings'}[id];if(req&&!can(req))return toast('لا تملك صلاحية الدخول إلى هذا القسم');if(id==='users'&&currentAccess?.role!=='admin')return toast('هذا القسم للمدير فقط');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));const names={home:'لوحة التحكم',cashier:'نقطة البيع',products:'إضافة مادة',inventory:'المخزون',repairs:'الصيانة',invoices:'الفواتير',debts:'الديون',reports:'الأرباح والتقارير',users:'المستخدمون',settings:'الإعدادات'};pageTitle.textContent=names[id];closeMenu();if(id==='home')renderHome();if(id==='products')renderProducts();if(id==='inventory')renderInventory();if(id==='invoices')renderInvoices();if(id==='users')renderUsers();if(id==='repairs'){if(!repairs.length)loadRepairs();else renderRepairs()}if(id==='cashier'){renderCart();renderPosResults()}}
function toggleMenu(){sidebar.classList.toggle('open');drawerOverlay.classList.toggle('show',sidebar.classList.contains('open'))}function closeMenu(){sidebar.classList.remove('open');drawerOverlay.classList.remove('show')}function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function renderHome(){const sales=invoices.reduce((a,b)=>a+b.total,0),low=products.filter(p=>p.qty<=p.alert).length;stats.innerHTML=[['مبيعات اليوم',money(sales)],['عدد الفواتير',invoices.length],['عدد المنتجات',products.length],['إجمالي القطع',products.reduce((a,b)=>a+b.qty,0)],['تنبيهات المخزون',low]].map(x=>`<div class="card stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');recentInvoices.innerHTML=invoices.slice(-6).reverse().map(i=>`<tr><td>${i.no}</td><td>${i.mode==='warranty'?'ضمان':'سريعة'}</td><td>${i.customer||'نقدي'}</td><td>${money(i.total)}</td><td><span class="badge">مدفوعة</span></td><td>${i.date}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد فواتير بعد</td></tr>'}

function toggleProductsMenu(){document.getElementById('productsSubmenu')?.classList.toggle('open')}
function openProductAdd(){go('products');document.getElementById('productsSubmenu')?.classList.add('open');setTimeout(()=>document.getElementById('productEntryPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
function renderInventory(){if(!window.inventoryBody)return;let q=(document.getElementById('inventorySearch')?.value||'').trim().toLowerCase();let cat=document.getElementById('inventoryCategory')?.value||'';const catMap={battery:'بطاريات',charger:'شواحن',dcdc:'DC to DC Converter',bms:'BMS',general:'مواد عامة'};let list=products.filter(p=>(!cat||p.category===catMap[cat])&&(!q||[p.barcode,p.name,p.category,p.maker,p.spec].join(' ').toLowerCase().includes(q)));inventoryBody.innerHTML=list.map(p=>`<tr><td>${p.barcode||'-'}</td><td>${p.name||'-'}</td><td>${p.category||'-'}</td><td>${p.maker||'-'}</td><td>${money(p.buy)}</td><td>${money(p.sale)}</td><td><b>${p.qty||0}</b></td><td>${p.warranty||0} شهر</td></tr>`).join('')||'<tr><td colspan="8" class="empty">لا توجد مواد في المخزون</td></tr>'}
