const firebaseConfig={apiKey:"AIzaSyC-EUCB1oycVqLU_yiV5CGFRhnN4DCvRYA",authDomain:"inventory-app-2cb3a.firebaseapp.com",databaseURL:"https://inventory-app-2cb3a-default-rtdb.firebaseio.com",projectId:"inventory-app-2cb3a",storageBucket:"inventory-app-2cb3a.firebasestorage.app",messagingSenderId:"901208724965",appId:"1:901208724965:web:a0ccc451e454853f914b0c",measurementId:"G-6XDZZMCR38"};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.database(),ADMIN_EMAIL='kadhim.pc.88@gmail.com';let currentUser=null,currentAccess=null;
function safeEmail(email){return (email||'').trim().toLowerCase().replace(/\./g,',')}
async function authorize(user){const email=(user.email||'').toLowerCase();if(email===ADMIN_EMAIL){currentAccess={role:'admin',permissions:{cashier:true,inventoryView:true,productAdd:true,productEdit:true,productDelete:true,barcodePrint:true,invoices:true,repairs:true,debts:true,reports:true,settings:true}};document.body.classList.add('is-admin');return true}const snap=await db.ref('allowedUsers/'+safeEmail(email)).once('value');if(!snap.exists()||snap.val().active===false)return false;currentAccess=snap.val();return true}
function can(p){if(currentAccess?.role==='admin')return true;const perms=currentAccess?.permissions||{};if(perms[p]===true)return true;if(perms.products===true&&['inventoryView','productAdd','productEdit','productDelete','barcodePrint'].includes(p))return true;return false}
function normalizeLegacy(v,k){return {id:v.id||k,barcode:v.barcode||'',name:v.name||'مادة',category:v.category||'مواد عامة',maker:v.maker||'',buy:Number(v.buy??v.buyPrice??0),sale:Number(v.sale??v.sellPrice??0),qty:Number(v.qty??0),alert:Number(v.alert??2),warranty:Number(v.warranty??0)}}
async function loadCloud(){const [ps,is,legacy]=await Promise.all([db.ref('products').once('value'),db.ref('invoices').once('value'),db.ref('inventory').once('value')]);const pv=ps.val()||{};products=Object.entries(pv).map(([k,v])=>normalizeLegacy(v,k));if(!products.length){const lv=legacy.val()||{};products=Object.entries(lv).map(([k,v])=>normalizeLegacy(v,k))}const iv=is.val()||{};invoices=Object.values(iv);renderProducts();renderInvoices();renderHome()}
async function cloudSaveAll(){if(!currentUser)return;const po={},io={};products.forEach(x=>po[String(x.id)]=x);invoices.forEach(x=>io[String(x.no).replace(/[.#$\[\]\/]/g,'_')]=x);await Promise.all([db.ref('products').set(po),db.ref('invoices').set(io)])}
async function addAllowedUser(){if(currentAccess?.role!=='admin')return;const email=newUserEmail.value.trim().toLowerCase();if(!email)return toast('اكتب Gmail الموظف');const permissions={cashier:permCashier.checked,inventoryView:permInventoryView.checked,productAdd:permProductAdd.checked,productEdit:permProductEdit.checked,productDelete:permProductDelete.checked,barcodePrint:permBarcodePrint.checked,invoices:permInvoices.checked,repairs:permRepairs.checked,debts:permDebts.checked,reports:permReports.checked};await db.ref('allowedUsers/'+safeEmail(email)).set({email,role:'employee',active:true,permissions,updatedAt:firebase.database.ServerValue.TIMESTAMP});newUserEmail.value='';renderUsers();toast('تمت إضافة المستخدم')}
async function renderUsers(){if(currentAccess?.role!=='admin')return;const q=await db.ref('allowedUsers').once('value'),obj=q.val()||{};const labels={cashier:'نقطة البيع',inventoryView:'عرض المخزون',productAdd:'إضافة مادة',productEdit:'تعديل مادة',productDelete:'حذف مادة',barcodePrint:'طباعة باركود',invoices:'الفواتير',repairs:'الصيانة',debts:'الديون',reports:'التقارير',products:'المنتجات (قديم)'};usersBody.innerHTML=Object.entries(obj).map(([id,u])=>{const p=Object.entries(u.permissions||{}).filter(x=>x[1]).map(x=>labels[x[0]]||x[0]).join('، ');return `<tr><td>${u.email}</td><td class="permissions-cell">${p||'بدون صلاحيات'}</td><td>${u.active===false?'موقوف':'مفعّل'}</td><td><button class="btn danger" onclick="removeAllowedUser('${id}')">إلغاء</button></td></tr>`}).join('')||'<tr><td colspan="4" class="empty">لا يوجد موظفون بعد</td></tr>'}
function setAllPermissions(v){['permInventoryView','permProductAdd','permProductEdit','permProductDelete','permBarcodePrint','permCashier','permInvoices','permRepairs','permDebts','permReports'].forEach(id=>{const e=document.getElementById(id);if(e)e.checked=v})}
async function removeAllowedUser(id){if(!confirm('إلغاء صلاحية هذا المستخدم؟'))return;await db.ref('allowedUsers/'+id).remove();renderUsers()}

document.getElementById('googleLogin').onclick=()=>auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(e=>authMsg.textContent='تعذر تسجيل الدخول: '+e.message);
auth.onAuthStateChanged(async user=>{if(!user)return;authMsg.textContent='جاري التحقق من الصلاحية...';try{if(!(await authorize(user))){authMsg.textContent='هذا الحساب غير مخوّل لاستخدام النظام. راجع المدير.';await auth.signOut();return}currentUser=user;authGate.style.display='none';const ue=document.querySelector('.user');if(ue)ue.innerHTML=`<div class="avatar">${(user.displayName||user.email||'U')[0]}</div><div><b>${user.displayName||'مستخدم'}</b><div class="user-email">${user.email}</div></div><button class="btn" onclick="auth.signOut().then(()=>location.reload())">خروج</button>`;applyPermissions();await loadCloud();await loadRepairs();if(currentAccess.role==='admin')renderUsers()}catch(e){authMsg.textContent='خطأ في الاتصال بقاعدة البيانات: '+e.message}});
function applyPermissions(){document.querySelectorAll('.nav button[data-page]').forEach(b=>{let ok=true;if(b.dataset.page==='cashier')ok=can('cashier');else if(b.dataset.page==='products')ok=can('productAdd');else if(b.dataset.page==='inventory')ok=can('inventoryView');else if(b.dataset.page==='invoices')ok=can('invoices');else if(b.dataset.page==='repairs')ok=can('repairs');else if(b.dataset.page==='debts')ok=can('debts');else if(b.dataset.page==='reports')ok=can('reports');else if(b.dataset.page==='settings')ok=can('settings');if(!ok)b.classList.add('perm-hidden')});const parent=document.querySelector('.nav-parent');if(parent&&!can('inventoryView')&&!can('productAdd'))parent.classList.add('perm-hidden');document.querySelectorAll('.quick button').forEach(b=>{const oc=b.getAttribute('onclick')||'';if(oc.includes("go('products')")&&!can('productAdd'))b.classList.add('perm-hidden');if(oc.includes("go('cashier')")&&!can('cashier'))b.classList.add('perm-hidden');if(oc.includes("go('repairs')")&&!can('repairs'))b.classList.add('perm-hidden');if(oc.includes("go('invoices')")&&!can('invoices'))b.classList.add('perm-hidden')})}
