function renderCart(){cartBody.innerHTML=cart.map(c=>`<tr><td>${c.name}</td><td><button class="btn" onclick="changeQty(${c.id},-1)">−</button> ${c.qty} <button class="btn" onclick="changeQty(${c.id},1)">＋</button></td><td>${money(c.price)}</td><td>${money(c.price*c.qty)}</td><td><button class="btn danger" onclick="removeCart(${c.id})">×</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">السلة فارغة</td></tr>';let sub=cart.reduce((a,c)=>a+c.price*c.qty,0),grand=Math.max(0,sub-(+discount.value||0));subTotal.textContent=money(sub);grandTotal.textContent=money(grand)}
function changeQty(id,d){let c=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);c.qty=Math.max(1,Math.min(p.qty,c.qty+d));renderCart()}function removeCart(id){cart=cart.filter(x=>x.id!==id);renderCart()}function clearCart(){cart=[];discount.value=0;renderCart()}
function saveInvoice(){if(!cart.length)return toast('أضف مادة إلى الفاتورة');if(invoiceMode==='warranty'&&!cName.value.trim())return toast('اسم العميل مطلوب لفاتورة الضمان');let sub=cart.reduce((a,c)=>a+c.price*c.qty,0),total=Math.max(0,sub-(+discount.value||0));let inv={no:'LP-'+String(Date.now()).slice(-8),createdAt:new Date().toISOString(),mode:invoiceMode,customer:invoiceMode==='warranty'?cName.value.trim():'',phone:invoiceMode==='warranty'?cPhone.value.trim():'',province:invoiceMode==='warranty'?cProvince.value.trim():'',area:invoiceMode==='warranty'?cArea.value.trim():'',date:new Date().toLocaleString('ar-IQ'),total,discount:+discount.value||0,items:JSON.parse(JSON.stringify(cart))};cart.forEach(c=>{let p=products.find(x=>x.id===c.id);p.qty-=c.qty});invoices.push(inv);save();buildPrint(inv);clearCart();renderHome();renderInvoices();toast('تم حفظ الفاتورة وفتح الطباعة');setTimeout(()=>window.print(),150)}
function buildPrint(i){let warranty=i.mode==='warranty';if(warranty){printArea.innerHTML=`<div class="warranty-sheet">
<div class="warranty-top"><div class="warranty-name-en">LITHIUM PRO</div><img class="warranty-logo" src="assets/logo.jpeg" style="width:46mm;height:31mm;object-fit:contain"></div>
<div class="warranty-title-row" style="display:flex;justify-content:flex-start;align-items:center;margin:1.5mm 0 2mm;direction:ltr"><div style="font-family:Arial,Tahoma,sans-serif;font-size:13px;font-weight:700;color:#1d232b">NO: ${i.no}</div></div>
<div class="warranty-meta"><div><b>اسم العميل:</b> ${i.customer||'-'}</div><div><b>رقم الهاتف:</b> ${i.phone||'-'}</div><div><b>المحافظة:</b> ${i.province||'-'}</div><div><b>المنطقة:</b> ${i.area||'-'}</div></div>
<table><thead><tr><th>المادة</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th><th>الضمان</th></tr></thead><tbody>${i.items.map(x=>`<tr><td>${x.name}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td><td>${x.warranty||0} شهر</td></tr>`).join('')}</tbody></table>
<div class="warranty-total">المبلغ الإجمالي: ${money(i.total)}</div>
<div class="warranty-terms"><b>شروط الضمان:</b><br>• يسري الضمان حسب المدة المثبتة لكل مادة في الفاتورة.<br>• يجب إبراز هذه الفاتورة عند المطالبة بالضمان.<br>• لا يشمل الضمان الضرر الناتج عن سوء الاستخدام أو التوصيل غير الصحيح أو الكسر والحرق الخارجي.</div>
<div class="warranty-footer">شكراً لاختياركم — نتمنى لكم تجربة موثوقة وآمنة.</div>
</div>`}else{printArea.innerHTML=`<div style="text-align:center;padding:4mm;width:80mm"><img src="assets/logo.jpeg" style="width:28mm;height:20mm;object-fit:contain"><h2 style="margin:2mm 0">ليثيوم برو</h2><div>${i.no} — ${i.date}</div><hr><table><tbody>${i.items.map(x=>`<tr><td>${x.name} × ${x.qty}</td><td>${money(x.qty*x.price)}</td></tr>`).join('')}</tbody></table><h3>الإجمالي: ${money(i.total)}</h3><div>شكراً لتعاملكم معنا</div></div>`}}
function renderInvoices(){invoiceBody.innerHTML=invoices.slice().reverse().map((i,idx)=>`<tr><td>${i.no}</td><td>${i.mode==='warranty'?'ضمان A4':'سريعة 80mm'}</td><td>${i.customer||'نقدي'}</td><td>${money(i.total)}</td><td>${i.date}</td><td><button class="btn" onclick="reprint('${i.no}')">طباعة</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد فواتير</td></tr>'}function reprint(no){let i=invoices.find(x=>x.no===no);buildPrint(i);window.print()}
